apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: manuelarango1229/frontfitfusion:latest
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "http://104.154.209.130:3000"
